### ISSUE TITLE
library kit field should be changed to selection list

### ISSUE THREAD

**Issue by luissian** [BU-ISCIII/iSkyLIMS_wetlab#12]
When selecting the library kit, this will be selected from a list containing the possible value

Allow that a new librari kit value was possible to add in the form.
https://selectize.github.io/selectize.js/

**Comment by saramonzon** [comment]
Create table in database: libraryKit
Columns: Library Name, version, batch id, Provider
Create form for visualize libraries, and add new one.
Select in upload form is populated by this table.

**Comment by luissian** [comment]
2 Tables have been created:
LibraryKit with columns libraryName, sampleNumber, indexNumber, 
LibKitInformation with columns batch_id, provider , expirationDate, librarykit_id

**Comment by luissian** [comment]
Only LibraryKit is created with a simple column 
The values in the table will be used to create the selected option list on HTML
the column LibraryKit_id has been added to wetlab_projects table as foreignKey to LibraryKit table
The previous records on database must update manually with the foreign Key 
The previous column ( libraryKit ) on wetlab_project will containg now the  library used to import the library on base space.

Graphics and statistics must be update to use the new columns of the library
