### ISSUE TITLE
Unique identifier in sample_id column

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS_wetlab#15]
Genomics Unit will supply sample_names. 
Sample_id unique identifiers mut be generated and added to in basespace library import file column. 
Sample_id unique identifiers format: 0000AA

**Comment by luissian** [comment]
Sample ID are created with the format 0000-AA
A file named index_file has been created to keep track the latest index used. File is located on the documents/wetlab directory
