### ISSUE TITLE
Time tracking for run states

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS_wetlab#26]
Add time tracking information in each change of state:
- Run recorded. 
- Run start . Date get from run_info.xml  file
- Run finish. Date/time from the cration of the runCompletion.xml file
- Bcl2fastq finish. Date/time from the creation of the structure generated by bcl2fastq 
- Process completed. Date from finish the process in iSkyLIMS

**Comment by luissian** [comment]
Code is implemented in parsing_run_info.py.
A new function update_tables_date is defined on views.py to update the information for the already recorded runs
