### ISSUE TITLE
File documents/wetlab/tmp/processed_run_file (flavia) contains just 4 processed runs

### ISSUE THREAD

**Issue by jlgarciapacheco** [BU-ISCIII/iSkyLIMS_wetlab#31]
At this moment there are just 4 (nextSeq) registered runs in the file. 
Among other things this conveys needless analysis of already processed runs (see logs)
Probably due to an accidental deletion of the file in the past.

Suggested fix: repopulate the file with already processed runs (that means runs having already reached 'Sample State' or a further one)

**Comment by luissian** [comment]
Most of the missing information have been already updated from an old backup file that I have in my local hard disk.
The remaining lost information it was updated manually.
