### ISSUE TITLE
Error string_message referenced before assigment

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS_wetlab#36]
Detected bug here:

https://github.com/BU-ISCIII/iSkyLIMS_wetlab/blob/40c859c0d89fc8ff15fd563e9015d431df8b65db/utils/miseq_run_functions.py#L645

Only raised when miseq run processing fails.

**Comment by luissian** [comment]
Bug Fixed by setting string_message variable to : 

string_message = new_run + 'Unable to save MiSeq Run  into Database'
