### ISSUE TITLE
Error variable not defined

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS_wetlab#37]
Bug detected, should be wetlab_config.FROM_EMAIL_ADDESS and the same in the next "variable"

https://github.com/BU-ISCIII/iSkyLIMS_wetlab/blob/81609631c37c3cb240d3e9ac2d05ed511616e45c/utils/generic_functions.py#L371

Only raised when sent_mail_on_error = True in wetlab_config

**Comment by luissian** [comment]
Bug fixed on develop branch 12-Dec-2019
