### ISSUE TITLE
Broken link: basespace file download in all places

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS_wetlab#5]
I had to use MEDIA_ROOT settings variable for referencing files for reading. This change makes that links redirect to wrong absolute path too and it doesn`t work for download.

**Comment by luissian** [comment]
Changes in sample_conversion file
---
Changed **dir** in dir =settings.MEDIA_ROOT by base_dir to avoid conflict with the dir function in Python  
Using the settngs.BASE_DIR to remove the absolute path and keeping the "documents" 

Changes in views file
---
This change is needed for setting  the **"write"** permission on the group to deleted the tmp/run_id folder, and the Sample Sheet file.  when contrab is executed on the django user.
temporary variable is create to simplify the settings when using the os.chmod command to provide write access to the folder and sample sheet file
