### ISSUE TITLE
Sample sheet import not working with one index

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS_wetlab#7]
[SampleSheet.txt](https://github.com/BU-ISCIII/iSkyLIMS-wetlab/files/1771759/SampleSheet.txt)

Example: 
160620_NS500454_0076_AHTHKGBGXX | NextSeq_CNM_026b | fjalonso | Scriptseq v2 RNA-Seq Library Preparation kit | Sólo un índice | Error

**Comment by luissian** [comment]
fixed
